id: P000630
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6915
  title: སྒྲ་བྲེ་བྲག་རྟོགས་བྱེད་ཆེན་མོ་སྐད་བཞི་ཤན་སྦྱར་མ།
  author: ''
  volumes:
    889aab6952fe4c27b7ab16ff995e58d5:
      image_group_id: I3CN6917
      title: ''
      volume_number: 1
      total_pages: 812
